## Python 生成器中yield.send（）容易出错的地方
* 首先强调在3.4以后生成器要调用next()方法已经改为__next__()
* 生成器初始化的时候要使用__next__()后才能正常生成，或者使用send(None)\
* 关于send()的理解
  先放一段原文：
```
    ## send(value)
      Resumes the execution and ``sends'' a value into the generator function. 
    The value argument becomes the result of the current yield expression. 
    The send() method returns the next value yielded by the generator, 
    or raises StopIteration if the generator exits without yielding another value. 
    When send() is called to start the generator, it must be called with None as the argument, 
    because there is no yield expression that could receieve the value.
```
  意思是：send(A)会往生成器里面的第一个yield或者后期后继续执行到下一个yield 后的参数发送一个A ，但是此时并不返回这个yield表达式
  的结果(并不返回yield A):例如
```
def countdown(n):
    yield n
    n+1
c=countdown(5)
c.__next__()
c.sen
```
  当
